import EnergyPageHero from "../../components/energy/page-hero";
import EnergyStatBand from "../../components/energy/stat-band";
import SiteFooter from "../../components/home/site-footer";
import DeferredVideo from "../../components/media/deferred-video";
import Navbar from "../../components/navbar";

const POWERWALL_BENEFITS = [
  {
    description:
      "Capture excess solar generation or charge from the grid when energy costs are lower.",
    title: "Store Extra Energy",
  },
  {
    description:
      "Use stored power during the day, at night or immediately when an outage occurs.",
    title: "Use Energy Anytime",
  },
  {
    description:
      "Optimize your system around utility rates and supported grid-service programs.",
    title: "Save and Support",
  },
];

const POWERWALL_SPECS = [
  ["Energy Capacity", "13.5 kWh"],
  ["On-Grid Power", "11.5 kW continuous"],
  ["Backup Power", "11.5 kW continuous"],
  ["Solar Efficiency", "97.5% solar-to-grid"],
  ["Operating Range", "-4°F to 122°F"],
  ["Warranty", "10 years"],
];

export default function PowerwallPage() {
  return (
    <div className="bg-white">
      <Navbar isBlurred isWhiteText />

      <main>
        <EnergyPageHero
          actions={[
            {
              external: true,
              href: "https://www.tesla.com/powerwall/design",
              label: "Order Powerwall 3",
            },
            {
              href: "#powerwall-specs",
              label: "View Specs",
              variant: "secondary",
            },
          ]}
          description="Store clean energy for use anytime, protect your home during outages and manage everything from the Tesla app."
          eyebrow="Home Battery Storage"
          image="/assets/tesla-official/powerwall-storm.avif"
          imageAlt="A home protected by Powerwall during severe weather"
          imageHeight={1200}
          title="Powerwall"
        />

        <EnergyStatBand
          stats={[
            { detail: "Battery Power", value: "6.7 GW" },
            { detail: "Energy Delivered", value: "17.3 TWh" },
            { detail: "Hours of Protection", value: "142.9M" },
            { detail: "Installed Globally", value: "1M+" },
          ]}
        />

        <section className="content-auto px-5 py-20 sm:px-8 lg:px-10">
          <div className="mx-auto max-w-7xl">
            <header className="mx-auto max-w-3xl text-center">
              <p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#5c5e62]">
                Power your home, save money
              </p>
              <h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">
                Energy when you need it
              </h2>
              <p className="mt-5 leading-7 text-[#5c5e62]">
                Powerwall stores energy generated by solar or from the grid and
                makes it available based on the needs of your home.
              </p>
            </header>

            <div className="mt-12 grid gap-4 lg:grid-cols-3">
              {POWERWALL_BENEFITS.map((benefit, index) => (
                <article
                  className="rounded-2xl bg-[#f4f4f4] p-8"
                  key={benefit.title}
                >
                  <p className="text-xs font-semibold tracking-[0.16em] text-[#a2a3a5]">
                    0{index + 1}
                  </p>
                  <h3 className="mt-10 text-2xl font-semibold tracking-[-0.025em]">
                    {benefit.title}
                  </h3>
                  <p className="mt-3 text-sm leading-6 text-[#5c5e62]">
                    {benefit.description}
                  </p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="content-auto bg-[#0b0c0e] px-5 py-20 text-white sm:px-8 lg:px-10">
          <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.35fr_0.65fr] lg:items-center">
            <div className="overflow-hidden rounded-2xl bg-[#17191c]">
              <DeferredVideo
                className="aspect-video h-full w-full object-cover"
                poster="/assets/tesla-official/energy-app-overview-poster.avif"
                src="/assets/tesla-official/energy-app-overview.mp4"
              />
            </div>
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.16em] text-white/50">
                Tesla app
              </p>
              <h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">
                Your energy at a glance
              </h2>
              <p className="mt-5 max-w-lg leading-7 text-white/65">
                Monitor solar production, home consumption and Powerwall charge
                level in real time. Change power modes and control how stored
                energy is used directly from your phone.
              </p>
            </div>
          </div>
        </section>

        <section className="content-auto grid bg-[#111214] text-white lg:grid-cols-2">
          <div className="relative min-h-[520px] overflow-hidden lg:min-h-[720px]">
            <img
              alt="Two Powerwall units installed against a concrete wall"
              className="absolute inset-0 h-full w-full object-cover"
              decoding="async"
              height="885"
              loading="lazy"
              src="/assets/tesla-official/powerwall-hero.avif"
              width="1920"
            />
          </div>
          <div className="flex flex-col justify-center px-7 py-14 sm:px-12 lg:px-16">
            <p className="text-sm font-semibold uppercase tracking-[0.16em] text-white/55">
              Maximum efficiency
            </p>
            <h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">
              Compact, integrated and scalable
            </h2>
            <p className="mt-5 max-w-lg leading-7 text-white/65">
              Powerwall 3 combines battery storage, a solar inverter and system
              controls in one weather-resistant unit that can expand with your
              energy needs.
            </p>
          </div>
        </section>

        <section
          className="content-auto bg-[#f4f4f4] px-5 py-20 sm:px-8 lg:px-10"
          id="powerwall-specs"
        >
          <div className="mx-auto max-w-7xl">
            <header className="max-w-2xl">
              <p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#5c5e62]">
                Powerwall 3
              </p>
              <h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">
                Specifications
              </h2>
            </header>

            <dl className="mt-12 grid overflow-hidden rounded-2xl bg-white sm:grid-cols-2 lg:grid-cols-3">
              {POWERWALL_SPECS.map(([label, value]) => (
                <div
                  className="border-b border-black/10 p-7 last:border-b-0 sm:border-r lg:[&:nth-child(3n)]:border-r-0"
                  key={label}
                >
                  <dt className="text-xs font-semibold uppercase tracking-[0.14em] text-[#5c5e62]">
                    {label}
                  </dt>
                  <dd className="mt-3 text-xl font-semibold text-[#171a20]">
                    {value}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        <section className="content-auto relative min-h-[76svh] overflow-hidden bg-[#111214] text-white">
          <img
            alt="A Tesla charging from solar energy stored in Powerwall"
            className="absolute inset-0 h-full w-full object-cover object-center"
            decoding="async"
            height="822"
            loading="lazy"
            src="/assets/tesla-official/charge-on-solar.avif"
            width="1920"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/35 to-transparent" />
          <div className="relative mx-auto flex min-h-[76svh] max-w-7xl items-center px-6 py-20 lg:px-10">
            <div className="max-w-xl">
              <p className="text-sm font-semibold uppercase tracking-[0.16em] text-white/60">
                Charge on solar
              </p>
              <h2 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">
                Energy that goes further
              </h2>
              <p className="mt-5 leading-7 text-white/70">
                Use excess solar production to charge your Tesla and keep clean
                energy moving between your home, vehicle and Powerwall.
              </p>
              <a
                className="mt-8 inline-flex rounded bg-white px-7 py-3 text-sm font-semibold text-[#171a20]"
                href="https://www.tesla.com/powerwall/design"
                rel="noreferrer"
                target="_blank"
              >
                Order Powerwall 3
              </a>
            </div>
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
